enabled: false
mode: sim
recording_rate_hz: 10
servers:
- name: ComApp
  host: 192.168.10.1
  port: 502
  unit_id: 1
  timeout_ms: 200
  max_retries: 3
writes: []
reads:
- alias: Room Temp
  fc: 4
  address: 30001
  length: 2
  data_type_input: float
  type: float32
  byte_order: big
  word_order: AB
  scaling:
    m: 1.0
    b: 0.0
    unit: C
  poll_hz: 10.0
  enabled: true
  server: ComApp
- alias: Humidity
  fc: 4
  address: 30002
  length: 2
  data_type_input: float
  type: float32
  byte_order: big
  word_order: AB
  scaling:
    m: 1.0
    b: 0.0
    unit: '%RH'
  poll_hz: 10.0
  enabled: true
  server: ComApp
- alias: WS_AmbientTemp
  fc: 3
  address: 0
  length: 1
  data_type_input: unsigned
  type: uint16
  byte_order: big
  word_order: AB
  scaling:
    m: 1.0
    b: 0.0
    unit: C
  poll_hz: 10.0
  enabled: true
  server: Omega Weather Station
connection:
  interface_type: TCP/IP
  ip_address: 192.168.10.1
  network_port: 502
  com_port: COM1
  unit_id: 1
  baud_rate: 115200
  serial_type: RTU
  word_order: big
devices:
- name: ComApp
  connection:
    interface_type: TCP/IP
    ip_address: 192.168.10.1
    network_port: 502
    com_port: COM1
    unit_id: 1
    baud_rate: 115200
    serial_type: RTU
    word_order: big
  reads:
  - alias: Room Temp
    fc: 4
    address: 30001
    length: 2
    data_type_input: float
    type: float32
    byte_order: big
    word_order: AB
    scaling:
      m: 1.0
      b: 0.0
      unit: C
    poll_hz: 10.0
    enabled: true
  - alias: Humidity
    fc: 4
    address: 30002
    length: 2
    data_type_input: float
    type: float32
    byte_order: big
    word_order: AB
    scaling:
      m: 1.0
      b: 0.0
      unit: '%RH'
    poll_hz: 10.0
    enabled: true
- name: Omega Weather Station
  connection:
    interface_type: RS485
    ip_address: ''
    network_port: 502
    com_port: COM1
    unit_id: 1
    baud_rate: 9600
    serial_type: RTU
    word_order: big
  reads:
  - alias: WS_AmbientTemp
    fc: 3
    address: 0
    length: 1
    data_type_input: unsigned
    type: uint16
    byte_order: big
    word_order: AB
    scaling:
      m: 1.0
      b: 0.0
      unit: C
    poll_hz: 10.0
    enabled: true
serial_devices:
- name: Omega Weather Station
  port: COM1
  unit_id: 1
  baud_rate: 9600
  serial_type: RTU
  word_order: big
