# Author: T. Onkst | Date: 08122025

mode: real  # real | sim
recording_rate_hz: 10

decimation:
  filter: IIR_Butterworth
  cutoff_hz: auto

watchdog:
  mode: driver
  driver:
    refresh_rate_hz: 2
    timeout_ms: 1000

channels: []


